spring:
  jpa:
    hibernate:
      ddl-auto: none
    show_sql: false
  datasource:
    hikari:
      jdbc-url: jdbc:mariadb://postservice.cahxymfhxkdm.ap-northeast-2.rds.amazonaws.com:3306/postservice
      username: g1063114
      password: CJH21147556!!
      driver-class-name: org.mariadb.jdbc.Driver
