spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 379086875766-0ofdi0hnq8un1gh8l0pip9f66qakhpg8.apps.googleusercontent.com
            client-secret: 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
            scope: profile,email
          naver:
            client-id: N_RigUxNAtOtEVdfYNnN
            client-secret: 6ic5AN6zGW
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            authorization_grant_type: authorization_code
            scope: name, email, profile_image
            client-name: Naver
        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response